[build]
  command = "npm install && npm run build"
  functions = "/"
  publish = "public"   # Adjust this line to point to your public folder containing index.ejs

[[redirects]]
  from = "/*"
  to = "/index.ejs"
  status = 200
